application: YOURAPPID
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: html/css

- url: /js
  static_dir: html/js

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

# webob 1.2.3 fix the file/text uploading issue with international characters in request
- name: webob
  version: latest 
